// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FhevmECDSA$Type } from "./FhevmECDSA";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FhevmECDSA"]: FhevmECDSA$Type;
    ["@fhevm/solidity/lib/cryptography/FhevmECDSA.sol:FhevmECDSA"]: FhevmECDSA$Type;
  }

  interface ContractTypesMap {
    ["FhevmECDSA"]: GetContractReturnType<FhevmECDSA$Type["abi"]>;
    ["@fhevm/solidity/lib/cryptography/FhevmECDSA.sol:FhevmECDSA"]: GetContractReturnType<FhevmECDSA$Type["abi"]>;
  }
}
