// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface FhevmECDSA$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "FhevmECDSA",
  "sourceName": "@fhevm/solidity/lib/cryptography/FhevmECDSA.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ECDSAInvalidSignature",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "length",
          "type": "uint256"
        }
      ],
      "name": "ECDSAInvalidSignatureLength",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "ECDSAInvalidSignatureS",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f3723c7d7ea8e65f6b49a1c5f48c809052484bc80893657a9d482bfa2db6901e64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f3723c7d7ea8e65f6b49a1c5f48c809052484bc80893657a9d482bfa2db6901e64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "FhevmECDSA",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FhevmECDSA$Type["abi"]>>;
  export function deployContract(
    contractName: "@fhevm/solidity/lib/cryptography/FhevmECDSA.sol:FhevmECDSA",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FhevmECDSA$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "FhevmECDSA",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FhevmECDSA$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@fhevm/solidity/lib/cryptography/FhevmECDSA.sol:FhevmECDSA",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FhevmECDSA$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "FhevmECDSA",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FhevmECDSA$Type["abi"]>>;
  export function getContractAt(
    contractName: "@fhevm/solidity/lib/cryptography/FhevmECDSA.sol:FhevmECDSA",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FhevmECDSA$Type["abi"]>>;
}
