// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Common$Type } from "./Common";
import { TFHE$Type } from "./TFHE";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Common"]: Common$Type;
    ["TFHE"]: TFHE$Type;
    ["fhevm/lib/TFHE.sol:Common"]: Common$Type;
    ["fhevm/lib/TFHE.sol:TFHE"]: TFHE$Type;
  }

  interface ContractTypesMap {
    ["Common"]: GetContractReturnType<Common$Type["abi"]>;
    ["TFHE"]: GetContractReturnType<TFHE$Type["abi"]>;
    ["fhevm/lib/TFHE.sol:Common"]: GetContractReturnType<Common$Type["abi"]>;
    ["fhevm/lib/TFHE.sol:TFHE"]: GetContractReturnType<TFHE$Type["abi"]>;
  }
}
