// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface TFHE$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "TFHE",
  "sourceName": "fhevm/lib/TFHE.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bd75ad1b323cb1d6016edfbf42e0e10ea8a02e6f945448366e58654d31302f6664736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bd75ad1b323cb1d6016edfbf42e0e10ea8a02e6f945448366e58654d31302f6664736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "TFHE",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TFHE$Type["abi"]>>;
  export function deployContract(
    contractName: "fhevm/lib/TFHE.sol:TFHE",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TFHE$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "TFHE",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TFHE$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "fhevm/lib/TFHE.sol:TFHE",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TFHE$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "TFHE",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TFHE$Type["abi"]>>;
  export function getContractAt(
    contractName: "fhevm/lib/TFHE.sol:TFHE",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TFHE$Type["abi"]>>;
}
