// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IACL$Type } from "./IACL";
import { IFHEVMExecutor$Type } from "./IFHEVMExecutor";
import { IInputVerifier$Type } from "./IInputVerifier";
import { Impl$Type } from "./Impl";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IACL"]: IACL$Type;
    ["IFHEVMExecutor"]: IFHEVMExecutor$Type;
    ["IInputVerifier"]: IInputVerifier$Type;
    ["Impl"]: Impl$Type;
    ["@fhevm/solidity/lib/Impl.sol:IACL"]: IACL$Type;
    ["@fhevm/solidity/lib/Impl.sol:IFHEVMExecutor"]: IFHEVMExecutor$Type;
    ["@fhevm/solidity/lib/Impl.sol:IInputVerifier"]: IInputVerifier$Type;
    ["@fhevm/solidity/lib/Impl.sol:Impl"]: Impl$Type;
  }

  interface ContractTypesMap {
    ["IACL"]: GetContractReturnType<IACL$Type["abi"]>;
    ["IFHEVMExecutor"]: GetContractReturnType<IFHEVMExecutor$Type["abi"]>;
    ["IInputVerifier"]: GetContractReturnType<IInputVerifier$Type["abi"]>;
    ["Impl"]: GetContractReturnType<Impl$Type["abi"]>;
    ["@fhevm/solidity/lib/Impl.sol:IACL"]: GetContractReturnType<IACL$Type["abi"]>;
    ["@fhevm/solidity/lib/Impl.sol:IFHEVMExecutor"]: GetContractReturnType<IFHEVMExecutor$Type["abi"]>;
    ["@fhevm/solidity/lib/Impl.sol:IInputVerifier"]: GetContractReturnType<IInputVerifier$Type["abi"]>;
    ["@fhevm/solidity/lib/Impl.sol:Impl"]: GetContractReturnType<Impl$Type["abi"]>;
  }
}
