// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IInputVerifier$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IInputVerifier",
  "sourceName": "@fhevm/solidity/lib/Impl.sol",
  "abi": [
    {
      "inputs": [],
      "name": "cleanTransientStorage",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IInputVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IInputVerifier$Type["abi"]>>;
  export function deployContract(
    contractName: "@fhevm/solidity/lib/Impl.sol:IInputVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IInputVerifier$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IInputVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IInputVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@fhevm/solidity/lib/Impl.sol:IInputVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IInputVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IInputVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IInputVerifier$Type["abi"]>>;
  export function getContractAt(
    contractName: "@fhevm/solidity/lib/Impl.sol:IInputVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IInputVerifier$Type["abi"]>>;
}
