// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConfidentialAlpha$Type } from "./ConfidentialAlpha";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConfidentialAlpha"]: ConfidentialAlpha$Type;
    ["contracts/ConfidentialAlpha.sol:ConfidentialAlpha"]: ConfidentialAlpha$Type;
  }

  interface ContractTypesMap {
    ["ConfidentialAlpha"]: GetContractReturnType<ConfidentialAlpha$Type["abi"]>;
    ["contracts/ConfidentialAlpha.sol:ConfidentialAlpha"]: GetContractReturnType<ConfidentialAlpha$Type["abi"]>;
  }
}
