// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IACL$Type } from "./IACL";
import { ITFHEExecutor$Type } from "./ITFHEExecutor";
import { Impl$Type } from "./Impl";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IACL"]: IACL$Type;
    ["ITFHEExecutor"]: ITFHEExecutor$Type;
    ["Impl"]: Impl$Type;
    ["fhevm/lib/Impl.sol:IACL"]: IACL$Type;
    ["fhevm/lib/Impl.sol:ITFHEExecutor"]: ITFHEExecutor$Type;
    ["fhevm/lib/Impl.sol:Impl"]: Impl$Type;
  }

  interface ContractTypesMap {
    ["IACL"]: GetContractReturnType<IACL$Type["abi"]>;
    ["ITFHEExecutor"]: GetContractReturnType<ITFHEExecutor$Type["abi"]>;
    ["Impl"]: GetContractReturnType<Impl$Type["abi"]>;
    ["fhevm/lib/Impl.sol:IACL"]: GetContractReturnType<IACL$Type["abi"]>;
    ["fhevm/lib/Impl.sol:ITFHEExecutor"]: GetContractReturnType<ITFHEExecutor$Type["abi"]>;
    ["fhevm/lib/Impl.sol:Impl"]: GetContractReturnType<Impl$Type["abi"]>;
  }
}
