// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IACL$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IACL",
  "sourceName": "fhevm/lib/Impl.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "handle",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allow",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256[]",
          "name": "handlesList",
          "type": "uint256[]"
        }
      ],
      "name": "allowForDecryption",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "ciphertext",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowTransient",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "cleanTransientStorage",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "handle",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IACL",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IACL$Type["abi"]>>;
  export function deployContract(
    contractName: "fhevm/lib/Impl.sol:IACL",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IACL$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IACL",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IACL$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "fhevm/lib/Impl.sol:IACL",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IACL$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IACL",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IACL$Type["abi"]>>;
  export function getContractAt(
    contractName: "fhevm/lib/Impl.sol:IACL",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IACL$Type["abi"]>>;
}
