// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Impl$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Impl",
  "sourceName": "fhevm/lib/Impl.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122068c2b3390c28ff8041bc726bb0e4a76b5b42a39ac5f67ef37df364928376db3d64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122068c2b3390c28ff8041bc726bb0e4a76b5b42a39ac5f67ef37df364928376db3d64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Impl",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Impl$Type["abi"]>>;
  export function deployContract(
    contractName: "fhevm/lib/Impl.sol:Impl",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Impl$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Impl",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Impl$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "fhevm/lib/Impl.sol:Impl",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Impl$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Impl",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Impl$Type["abi"]>>;
  export function getContractAt(
    contractName: "fhevm/lib/Impl.sol:Impl",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Impl$Type["abi"]>>;
}
