// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FHE$Type } from "./FHE";
import { IKMSVerifier$Type } from "./IKMSVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FHE"]: FHE$Type;
    ["IKMSVerifier"]: IKMSVerifier$Type;
    ["@fhevm/solidity/lib/FHE.sol:FHE"]: FHE$Type;
    ["@fhevm/solidity/lib/FHE.sol:IKMSVerifier"]: IKMSVerifier$Type;
  }

  interface ContractTypesMap {
    ["FHE"]: GetContractReturnType<FHE$Type["abi"]>;
    ["IKMSVerifier"]: GetContractReturnType<IKMSVerifier$Type["abi"]>;
    ["@fhevm/solidity/lib/FHE.sol:FHE"]: GetContractReturnType<FHE$Type["abi"]>;
    ["@fhevm/solidity/lib/FHE.sol:IKMSVerifier"]: GetContractReturnType<IKMSVerifier$Type["abi"]>;
  }
}
